addSbtPlugin("com.geirsson"      % "sbt-ci-release"         % "1.5.7")
addSbtPlugin("io.chrisdavenport" % "sbt-mima-version-check" % "0.1.2")
addSbtPlugin("io.chrisdavenport" % "sbt-no-publish"         % "0.1.0")
addSbtPlugin("com.47deg"         % "sbt-microsites"         % "1.3.4")
addSbtPlugin("org.scalameta"     % "sbt-mdoc"               % "2.2.20")
addSbtPlugin("org.scalameta"     % "sbt-scalafmt"           % "2.4.2")
addSbtPlugin("de.heikoseeberger" % "sbt-header"             % "5.6.0")
